---
# aap-demo: set ansible_host to your AAP VM when using AAP playbooks
all:
  children:
    aap_controllers:
      hosts:
        aap-demo:
          ansible_host: 192.168.4.CHANGEME
          ansible_user: cloud-user
