apiVersion: flightctl.io/v1beta1
kind: ResourceSync
metadata:
  name: technitium-dns-sync
spec:
  repository: flightctl
  path: /applications/technitium-dns/deployment/fleet-dns.yaml
  targetRevision: main