global:
  baseDomain: rhem.rhem-eap.lan
  generateCertificates: builtin
  auth:
    type: oidc
    insecureSkipTlsVerify: true
    aap:
      apiUrl:
      externalApiUrl:
      oAuthApplicationClientId:
      oAuthToken:
    oidc:
      clientId: flightctl-client
      clientSecret:
      enabled: true
      issuer: http://keycloak.rhem-eap.lan:8080/realms/edge-manager
      externalOidcAuthority: http://keycloak.rhem-eap.lan:8080/realms/edge-manager
      organizationAssignment:
        type: static
        organizationName: default
      usernameClaim:
        - preferred_username
      roleAssignment:
        type: dynamic
        separator: ":"
        claimPath:
          - realm_access
          - roles
    pamOidcIssuer:
      enabled: false
      issuer:
      clientId: flightctl-client
      clientSecret:
      scopes:
        - openid
        - profile
        - email
        - roles
        - offline_access
      pamService: flightctl

db:
  name: flightctl
  type: builtin

service:
  rateLimit:
    enabled: true
    requests: 300
    window: 1m
    authRequests: 20
    authWindow: 1h
    trustedProxies: []

observability:
  grafana:
    image:
    published_port:
    oauth:
      enabled:
      provider_type:
      auth_url:
      token_url:
      api_url:
      scopes:
      client_id:
    local_admin_user:
    local_admin_password:
    root_url:
  prometheus:
    image:
  telemetry_gateway:
    image:
    prometheus_port:
    grpc_port:
    config:
      telemetryGateway:
        export:
          prometheus:
        forward:
          endpoint:
  userinfo_proxy:
    image:
    upstream_url:
    skip_tls_verify:
