apiVersion: flightctl.io/v1beta1
kind: ResourceSync
metadata:
  name: flightctl-frigate-proxmox-sync
spec:
  repository: flightctl
  path: /applications/frigate-nvr-proxmox/deployment/fleet-with-app.yaml
  targetRevision: main
